import { defineTable } from "convex/server";
import { v } from "convex/values";

export const allergyState = v.union(v.literal("unknown"), v.literal("not_provided"), v.literal("none"), v.literal("provided"));
export const referenceSource = v.object({ label: v.string(), documentId: v.optional(v.id("records")), versionId:v.optional(v.id("recordVersions")), page: v.optional(v.number()) });
export const medicineStatus = v.union(v.literal("current"), v.literal("archived"), v.literal("uncertain"), v.literal("discontinued"));
export const medicineFields = { name: v.string(), strength: v.optional(v.string()), route: v.optional(v.string()), instructions: v.string(), prescriber: v.string(), purpose: v.string(), source: referenceSource, status: medicineStatus, reviewNote: v.string() };
export const providerFields = { name: v.string(), role: v.string(), organization: v.string(), phone: v.string(), email: v.string(), address: v.string(), note: v.string(), emergencyContact: v.boolean() };
const householdId = v.id("households"), userId = v.id("users"), meta = { householdId, version: v.number(), createdBy: userId, updatedAt: v.number() };
export const replacementTarget = v.union(v.object({kind:v.literal("task"),id:v.id("tasks")}),v.object({kind:v.literal("coverage"),id:v.id("coverage")}));
export const followUpStatus = v.union(v.literal("waiting"),v.literal("received"),v.literal("closed"));
export const careTables = {
 handoverCareSnapshots:defineTable({householdId,handoverId:v.id("handovers"),senderId:userId,recipientId:userId,snapshot:v.string(),sourceDocumentIds:v.array(v.id("records")),fingerprint:v.string(),capturedAt:v.number(),since:v.number(),acceptedFingerprint:v.optional(v.string()),acceptedFollowUpIds:v.optional(v.array(v.id("followUps")))}).index("by_householdId",["householdId"]).index("by_handoverId",["handoverId"]),
 careProfiles: defineTable({ ...meta, preferredName:v.string(), insuranceReference:v.optional(v.string()), pharmacy:v.optional(v.string()), dateOfBirth:v.string(), allergiesState:allergyState, allergies:v.string(), conditions:v.string(), preferences:v.string(), communication:v.string(), emergencyInstructions:v.string(), authorizedUserIds:v.array(userId), authorityStatement:v.string(), authorityConfirmedAt:v.number(), reviewedBy:userId, reviewedAt:v.number() }).index("by_householdId",["householdId"]),
 careProviders: defineTable({ ...meta, ...providerFields }).index("by_householdId",["householdId"]),
 medicineEntries: defineTable({ ...meta, ...medicineFields, reviewedBy:userId, reviewedAt:v.number() }).index("by_householdId",["householdId"]).index("by_householdId_and_status",["householdId","status"]),
 medicineVersions: defineTable({ householdId, medicineId:v.id("medicineEntries"), ...medicineFields, version:v.number(), reviewedBy:userId, reviewedAt:v.number() }).index("by_householdId",["householdId"]).index("by_medicineId_and_version",["medicineId","version"]),
 careNotes: defineTable({ ...meta, body:v.string(), occurredAt:v.number(), visitId:v.optional(v.id("visits")), source:referenceSource }).index("by_householdId",["householdId"]).index("by_householdId_and_occurredAt",["householdId","occurredAt"]).index("by_householdId_and_updatedAt",["householdId","updatedAt"]).index("by_visitId",["visitId"]),
 visitQuestions: defineTable({ ...meta, visitId:v.id("visits"), question:v.string(), answer:v.string(), status:v.union(v.literal("open"),v.literal("answered")), source:referenceSource }).index("by_householdId",["householdId"]).index("by_visitId",["visitId"]),
 visitPacks: defineTable({ ...meta, visitId:v.id("visits"), summary:v.string(), readerIds:v.optional(v.array(userId)), sourceDocumentIds:v.optional(v.array(v.id("records"))), documentIds:v.array(v.id("records")), includeMedicines:v.boolean(), includeProfile:v.boolean(), reviewedBy:userId, reviewedAt:v.number(), snapshot:v.string() }).index("by_householdId",["householdId"]).index("by_visitId_and_version",["visitId","version"]),
 followUpReads:defineTable({householdId,followUpId:v.id("followUps"),userId,seenRevision:v.number(),seenAt:v.number()}).index("by_householdId",["householdId"]).index("by_followUpId_and_userId",["followUpId","userId"]),
 followUps: defineTable({ ...meta,mailRevision:v.optional(v.number()),latestMailAt:v.optional(v.number()),recordIds:v.optional(v.array(v.id("records"))), title:v.string(), detail:v.string(), requestedAt:v.optional(v.number()), contactId:v.optional(v.id("careProviders")), ownerId:userId, dueAt:v.number(), status:followUpStatus, visitId:v.optional(v.id("visits")), taskId:v.optional(v.id("tasks")), source:referenceSource, resolution:v.string(), resolvedAt:v.optional(v.number()), resolvedBy:v.optional(userId) }).index("by_householdId",["householdId"]).index("by_householdId_and_status_and_dueAt",["householdId","status","dueAt"]).index("by_visitId",["visitId"]),
 memberAvailability: defineTable({ ...meta, userId, startsAt:v.number(), endsAt:v.number(), state:v.union(v.literal("available"),v.literal("unavailable")), note:v.string() }).index("by_householdId",["householdId"]).index("by_householdId_and_startsAt",["householdId","startsAt"]).index("by_householdId_and_userId_and_startsAt",["householdId","userId","startsAt"]),
 replacementRequests: defineTable({ ...meta, target:replacementTarget, targetVersion:v.number(), previousOwnerId:userId, requestedMemberId:v.union(userId,v.null()), reason:v.string(), status:v.union(v.literal("open"),v.literal("accepted"),v.literal("declined"),v.literal("cancelled")), resolvedBy:v.optional(userId), resolvedAt:v.optional(v.number()) }).index("by_householdId",["householdId"]).index("by_householdId_and_status",["householdId","status"]).index("by_target_and_status",["target","status"]).index("by_householdId_and_requestedMemberId_and_status",["householdId","requestedMemberId","status"]),
};
