import {mailUnread,visibleFollowUp} from "./followUpMailAccess";
import { paginationOptsValidator, paginationResultValidator } from "convex/server";
import { v } from "convex/values";
import type { Doc, Id } from "./_generated/dataModel";
import schema from "./schema";
import { userQuery,userMutation,member,isLimitedHelper,activeAssignee,checkVersion,fail,text,timestamp,range,type UserMutationCtx,type UserQueryCtx } from "./model/access";
import { priorRequest,saveRequest } from "./model/requests";
import { record, notify } from "./model/events";
import { allergyState,medicineStatus,medicineFields,providerFields,referenceSource,followUpStatus,replacementTarget } from "./careSchema";
import { canReadCare,requireHealthAccess,canReadCareSource,canReadVisitPack } from "./careAccess";
import { recordAccess } from "./recordsAccess";

const hid={householdId:v.id("households")}, nullableId=v.union(v.id("users"),v.null());
async function visitFor(ctx:UserQueryCtx|UserMutationCtx,householdId:Id<"households">,visitId?:Id<"visits">){if(!visitId)return null;const row=await ctx.db.get(visitId);if(!row||row.householdId!==householdId) return fail("NOT_FOUND","Visit unavailable.");return row;}
async function sourceFor(ctx:UserQueryCtx|UserMutationCtx,householdId:Id<"households">,source:{label:string;documentId?:Id<"records">;versionId?:Id<"recordVersions">;page?:number}){
 let versionId=source.versionId;
 if(source.documentId){const row=await recordAccess(ctx,source.documentId);if(row.householdId!==householdId)fail("NOT_FOUND","Record unavailable.");versionId??=row.currentVersionId;if(versionId){const version=await ctx.db.get(versionId);if(!version||version.recordId!==row._id)fail("NOT_FOUND","Source version unavailable.");}}else if(versionId)fail("INVALID_SOURCE","Choose the source record for this version.");
 if(source.page!==undefined&&(!Number.isSafeInteger(source.page)||source.page<1||source.page>1000))fail("INVALID_PAGE","Choose a page between 1 and 1000.");
 return {...source,...(versionId?{versionId}:{}),label:text(source.label,"Source",300,true)};
}
async function priorId<T extends "medicineEntries"|"careProviders"|"careNotes"|"visitQuestions"|"visitPacks"|"followUps"|"memberAvailability"|"replacementRequests">(ctx:UserMutationCtx,table:T,requestId:string,args:unknown){const p=await priorRequest(ctx,`care.${table}`,requestId,JSON.stringify(args));if(!p)return null;const id=ctx.db.normalizeId(table,p.resultId);if(!id)fail("NOT_FOUND","Saved item unavailable.");return id;}
async function remember(ctx:UserMutationCtx,table:string,requestId:string,args:unknown,id:string){await saveRequest(ctx,`care.${table}`,requestId,JSON.stringify(args),id);}
const profileFields={preferredName:v.string(),insuranceReference:v.optional(v.string()),pharmacy:v.optional(v.string()),dateOfBirth:v.string(),allergiesState:allergyState,allergies:v.string(),conditions:v.string(),preferences:v.string(),communication:v.string(),emergencyInstructions:v.string(),authorityStatement:v.string(),authorizedUserIds:v.array(v.id("users"))};
export const getProfile=userQuery({args:hid,returns:v.object({profile:v.union(schema.doc("careProfiles"),v.null()),access:v.union(v.literal("setup"),v.literal("allowed"),v.literal("restricted")),canManageAccess:v.boolean()}),handler:async(ctx,args)=>{const {household}=await member(ctx,args.householdId);const p=await ctx.db.query("careProfiles").withIndex("by_householdId",q=>q.eq("householdId",args.householdId)).unique();if(!p)return {profile:null,access:household.ownerId===ctx.user._id?"setup" as const:"restricted" as const,canManageAccess:household.ownerId===ctx.user._id};const allowed=await canReadCare(ctx,args.householdId,ctx.user._id);return {profile:allowed?p:null,access:allowed?"allowed" as const:"restricted" as const,canManageAccess:p.createdBy===ctx.user._id};}});
export const saveProfile=userMutation({args:{...hid,...profileFields,expectedVersion:v.number()},returns:v.id("careProfiles"),handler:async(ctx,args)=>{
 const {household}=await member(ctx,args.householdId);const old=await ctx.db.query("careProfiles").withIndex("by_householdId",q=>q.eq("householdId",args.householdId)).unique();
 if(old){await requireHealthAccess(ctx,args.householdId,true);checkVersion(old,args.expectedVersion);if(old.createdBy!==ctx.user._id && JSON.stringify([...old.authorizedUserIds].sort())!==JSON.stringify([...args.authorizedUserIds].sort()))fail("FORBIDDEN","Only the profile creator can change access.");}else if(household.ownerId!==ctx.user._id||args.expectedVersion!==0)fail("FORBIDDEN","The household owner must create the care profile.");
 const readers=[...new Set(args.authorizedUserIds)];if(readers.length>20)fail("LIMIT","Choose at most twenty members.");for(const id of readers){await activeAssignee(ctx,args.householdId,id);if(await isLimitedHelper(ctx,args.householdId,id))fail("LIMITED_HELPER_ACCESS","Limited helpers cannot receive access to medical care information.");}
 if(args.dateOfBirth && (!/^\d{4}-\d{2}-\d{2}$/.test(args.dateOfBirth)||Number.isNaN(Date.parse(args.dateOfBirth))||Date.parse(args.dateOfBirth)>Date.now()||new Date(args.dateOfBirth).toISOString().slice(0,10)!==args.dateOfBirth))fail("INVALID_DATE","Enter a valid birth date.");
 if(args.allergiesState!=="provided" && args.allergies.trim())fail("INVALID_ALLERGIES","Choose Provided when adding allergy details.");
 const fields={preferredName:text(args.preferredName,"Preferred name",160),insuranceReference:text(args.insuranceReference??"","Insurance reference",2000,true),pharmacy:text(args.pharmacy??"","Pharmacy",1000,true),dateOfBirth:args.dateOfBirth,allergiesState:args.allergiesState,allergies:text(args.allergies,"Allergies",4000,args.allergiesState!=="provided"),conditions:text(args.conditions,"Conditions",4000,true),preferences:text(args.preferences,"Preferences",4000,true),communication:text(args.communication,"Communication",2000,true),emergencyInstructions:text(args.emergencyInstructions,"Emergency instructions",2000,true),authorityStatement:text(args.authorityStatement,"Authority statement",2000),authorizedUserIds:readers,authorityConfirmedAt:old&&old.authorityStatement===args.authorityStatement.trim()?old.authorityConfirmedAt:Date.now(),reviewedBy:ctx.user._id,reviewedAt:Date.now(),updatedAt:Date.now(),version:(old?.version??0)+1};
 if(old){await ctx.db.patch(old._id,fields);return old._id;}return ctx.db.insert("careProfiles",{...fields,householdId:args.householdId,createdBy:ctx.user._id});
}});
export const listMedicines=userQuery({args:{...hid,status:v.optional(medicineStatus)},returns:v.array(schema.doc("medicineEntries")),handler:async(ctx,args)=>{await requireHealthAccess(ctx,args.householdId);const rows=await ctx.db.query("medicineEntries").withIndex("by_householdId_and_status",q=>q.eq("householdId",args.householdId).eq("status",args.status??"current")).take(201);if(rows.length>200)fail("LIMIT","Archive older medicine references before adding more.");const allowed=await Promise.all(rows.map(r=>canReadCareSource(ctx,r.source,ctx.user._id)));return rows.filter((_,i)=>allowed[i]);}});
export const saveMedicine=userMutation({args:{...hid,...medicineFields,medicineId:v.optional(v.id("medicineEntries")),expectedVersion:v.optional(v.number()),requestId:v.string()},returns:v.id("medicineEntries"),handler:async(ctx,args)=>{await requireHealthAccess(ctx,args.householdId,true);const prior=await priorId(ctx,"medicineEntries",args.requestId,args);if(prior)return prior;const old=args.medicineId?await ctx.db.get(args.medicineId):null;if(args.medicineId&&(!old||old.householdId!==args.householdId))fail("NOT_FOUND","Medicine unavailable.");if(old){checkVersion(old,args.expectedVersion??0);if(!await canReadCareSource(ctx,old.source,ctx.user._id))fail("FORBIDDEN","Source access required.");}
 if(!old||old.status!==args.status){const rows=await ctx.db.query("medicineEntries").withIndex("by_householdId_and_status",q=>q.eq("householdId",args.householdId).eq("status",args.status)).take(200);if(rows.length>=200)fail("LIMIT","This status can contain up to two hundred medicine references.");}
 const fields={name:text(args.name,"Medicine",160),strength:text(args.strength??"","Strength",200,true),route:text(args.route??"","Route",200,true),instructions:text(args.instructions,"Reference instructions",3000,true),prescriber:text(args.prescriber,"Prescriber",200,true),purpose:text(args.purpose,"Purpose",1000,true),source:await sourceFor(ctx,args.householdId,args.source),status:args.status,reviewNote:text(args.reviewNote,"Review note",2000,true),version:(old?.version??0)+1,reviewedBy:ctx.user._id,reviewedAt:Date.now()};
 const id=old?old._id:await ctx.db.insert("medicineEntries",{...fields,householdId:args.householdId,createdBy:ctx.user._id,updatedAt:Date.now()});if(old)await ctx.db.patch(id,{...fields,updatedAt:Date.now()});await ctx.db.insert("medicineVersions",{...fields,householdId:args.householdId,medicineId:id});await remember(ctx,"medicineEntries",args.requestId,args,id);return id;}});
export const medicineHistory=userQuery({args:{medicineId:v.id("medicineEntries"),paginationOpts:paginationOptsValidator},returns:paginationResultValidator(schema.doc("medicineVersions")),handler:async(ctx,args)=>{const row=await ctx.db.get(args.medicineId);if(!row)fail("NOT_FOUND","Medicine unavailable.");await requireHealthAccess(ctx,row.householdId);const result=await ctx.db.query("medicineVersions").withIndex("by_medicineId_and_version",q=>q.eq("medicineId",row._id)).order("desc").paginate(args.paginationOpts);const can=await Promise.all(result.page.map(r=>canReadCareSource(ctx,r.source,ctx.user._id)));return {...result,page:result.page.filter((_,i)=>can[i])};}});
export const listProviders=userQuery({args:hid,returns:v.array(schema.doc("careProviders")),handler:async(ctx,args)=>{await requireHealthAccess(ctx,args.householdId);const rows=await ctx.db.query("careProviders").withIndex("by_householdId",q=>q.eq("householdId",args.householdId)).take(101);if(rows.length>100)fail("LIMIT","Reduce the provider list to one hundred contacts.");return rows;}});
export const saveProvider=userMutation({args:{...hid,...providerFields,providerId:v.optional(v.id("careProviders")),expectedVersion:v.optional(v.number()),requestId:v.string()},returns:v.id("careProviders"),handler:async(ctx,args)=>{await requireHealthAccess(ctx,args.householdId,true);const prior=await priorId(ctx,"careProviders",args.requestId,args);if(prior)return prior;const old=args.providerId?await ctx.db.get(args.providerId):null;if(args.providerId&&(!old||old.householdId!==args.householdId))fail("NOT_FOUND","Provider unavailable.");if(old)checkVersion(old,args.expectedVersion??0);else{const rows=await ctx.db.query("careProviders").withIndex("by_householdId",q=>q.eq("householdId",args.householdId)).take(100);if(rows.length>=100)fail("LIMIT","Keep up to one hundred care contacts.");}const fields={name:text(args.name,"Name",160),role:text(args.role,"Role",160,true),organization:text(args.organization,"Organization",200,true),phone:text(args.phone,"Phone",100,true),email:text(args.email,"Email",254,true),address:text(args.address,"Address",1000,true),note:text(args.note,"Note",2000,true),emergencyContact:args.emergencyContact,version:(old?.version??0)+1,updatedAt:Date.now()};const id=old?old._id:await ctx.db.insert("careProviders",{...fields,householdId:args.householdId,createdBy:ctx.user._id});if(old)await ctx.db.patch(id,fields);await remember(ctx,"careProviders",args.requestId,args,id);return id;}});
export const removeProvider=userMutation({args:{providerId:v.id("careProviders"),expectedVersion:v.number()},returns:v.null(),handler:async(ctx,args)=>{const row=await ctx.db.get(args.providerId);if(!row)return null;await requireHealthAccess(ctx,row.householdId,true);checkVersion(row,args.expectedVersion);await ctx.db.delete(row._id);return null;}});
export const listNotes=userQuery({args:{...hid,paginationOpts:paginationOptsValidator},returns:paginationResultValidator(schema.doc("careNotes")),handler:async(ctx,args)=>{await requireHealthAccess(ctx,args.householdId);const result=await ctx.db.query("careNotes").withIndex("by_householdId_and_occurredAt",q=>q.eq("householdId",args.householdId)).order("desc").paginate(args.paginationOpts);const can=await Promise.all(result.page.map(r=>canReadCareSource(ctx,r.source,ctx.user._id)));return {...result,page:result.page.filter((_,i)=>can[i])};}});
export const addNote=userMutation({args:{...hid,body:v.string(),occurredAt:v.number(),visitId:v.optional(v.id("visits")),source:referenceSource,requestId:v.string()},returns:v.id("careNotes"),handler:async(ctx,args)=>{await requireHealthAccess(ctx,args.householdId,true);const prior=await priorId(ctx,"careNotes",args.requestId,args);if(prior)return prior;await visitFor(ctx,args.householdId,args.visitId);const id=await ctx.db.insert("careNotes",{householdId:args.householdId,body:text(args.body,"Note",6000),occurredAt:timestamp(args.occurredAt),...(args.visitId?{visitId:args.visitId}:{}),source:await sourceFor(ctx,args.householdId,args.source),version:1,createdBy:ctx.user._id,updatedAt:Date.now()});await remember(ctx,"careNotes",args.requestId,args,id);return id;}});
export const removeNote=userMutation({args:{noteId:v.id("careNotes"),expectedVersion:v.number()},returns:v.null(),handler:async(ctx,args)=>{const row=await ctx.db.get(args.noteId);if(!row)return null;await requireHealthAccess(ctx,row.householdId,true);checkVersion(row,args.expectedVersion);if(!await canReadCareSource(ctx,row.source,ctx.user._id))fail("FORBIDDEN","Source access required.");await ctx.db.delete(row._id);return null;}});

export const listVisitQuestions = userQuery({
 args:{visitId:v.id("visits")},returns:v.array(schema.doc("visitQuestions")),
 handler:async(ctx,args)=>{
  const visit=await ctx.db.get(args.visitId);if(!visit)fail("NOT_FOUND","Visit unavailable.");await requireHealthAccess(ctx,visit.householdId);
  const rows=await ctx.db.query("visitQuestions").withIndex("by_visitId",q=>q.eq("visitId",visit._id)).take(101);
  if(rows.length>100)fail("LIMIT","Keep each visit to one hundred questions.");
  const allowed=await Promise.all(rows.map(r=>canReadCareSource(ctx,r.source,ctx.user._id)));return rows.filter((_,i)=>allowed[i]);
 }
});
export const saveVisitQuestion=userMutation({
 args:{...hid,visitId:v.id("visits"),question:v.string(),answer:v.string(),status:v.union(v.literal("open"),v.literal("answered")),source:referenceSource,questionId:v.optional(v.id("visitQuestions")),expectedVersion:v.optional(v.number()),requestId:v.string()},returns:v.id("visitQuestions"),
 handler:async(ctx,args)=>{
  await requireHealthAccess(ctx,args.householdId,true);await visitFor(ctx,args.householdId,args.visitId);
  const prior=await priorId(ctx,"visitQuestions",args.requestId,args);if(prior)return prior;
  const old=args.questionId?await ctx.db.get(args.questionId):null;
  if(args.questionId&&(!old||old.householdId!==args.householdId||old.visitId!==args.visitId))fail("NOT_FOUND","Question unavailable.");
  if(old){checkVersion(old,args.expectedVersion??0);if(!await canReadCareSource(ctx,old.source,ctx.user._id))fail("FORBIDDEN","Source access required.");}
  if(!old){const count=await ctx.db.query("visitQuestions").withIndex("by_visitId",q=>q.eq("visitId",args.visitId)).take(100);if(count.length>=100)fail("LIMIT","Each visit can contain up to one hundred questions.");}
  const fields={question:text(args.question,"Question",2000),answer:text(args.answer,"Answer",4000,args.status!=="answered"),status:args.status,source:await sourceFor(ctx,args.householdId,args.source),version:(old?.version??0)+1,updatedAt:Date.now()};
  const id=old?old._id:await ctx.db.insert("visitQuestions",{...fields,householdId:args.householdId,visitId:args.visitId,createdBy:ctx.user._id});if(old)await ctx.db.patch(id,fields);
  await remember(ctx,"visitQuestions",args.requestId,args,id);return id;
 }
});
export const removeVisitQuestion=userMutation({args:{questionId:v.id("visitQuestions"),expectedVersion:v.number()},returns:v.null(),handler:async(ctx,args)=>{const row=await ctx.db.get(args.questionId);if(!row)return null;await requireHealthAccess(ctx,row.householdId,true);checkVersion(row,args.expectedVersion);if(!await canReadCareSource(ctx,row.source,ctx.user._id))fail("FORBIDDEN","Source access required.");await ctx.db.delete(row._id);return null;}});

async function packReaders(ctx:UserMutationCtx,householdId:Id<"households">,ids:Id<"users">[],sourceDocumentIds:Id<"records">[]) {
 const readers=[...new Set(ids)];if(readers.length>20)fail("LIMIT","Choose at most twenty readers.");
 for(const id of readers){await activeAssignee(ctx,householdId,id);if(!await canReadCare(ctx,householdId,id))fail("CARE_ACCESS_REQUIRED","Every pack recipient needs access to the care profile first.");for(const documentId of sourceDocumentIds)if(!await canReadCareSource(ctx,{documentId},id))fail("SOURCE_ACCESS_REQUIRED","Give each recipient access to every included source record before sharing the pack.");}
 return readers;
}
export const createVisitPack=userMutation({
 args:{...hid,visitId:v.id("visits"),summary:v.string(),documentIds:v.array(v.id("records")),questionIds:v.optional(v.array(v.id("visitQuestions"))),noteIds:v.optional(v.array(v.id("careNotes"))),includeMedicines:v.boolean(),includeProfile:v.boolean(),readerIds:v.optional(v.array(v.id("users"))),requestId:v.string()},returns:v.id("visitPacks"),
 handler:async(ctx,args)=>{
  const profile=await requireHealthAccess(ctx,args.householdId,true),visit=await visitFor(ctx,args.householdId,args.visitId);if(!visit)fail("NOT_FOUND","Visit unavailable.");
  const prior=await priorId(ctx,"visitPacks",args.requestId,args);if(prior)return prior;
  const documentIds=[...new Set(args.documentIds)];if(documentIds.length>30)fail("LIMIT","Choose at most thirty records for one pack.");
  const sources=new Set<Id<"records">>(documentIds),documents=[];
  for(const id of documentIds){const doc=await recordAccess(ctx,id);if(doc.householdId!==args.householdId)fail("NOT_FOUND","Record unavailable.");documents.push({id:doc._id,title:doc.title,category:doc.category,documentDate:doc.documentDate??"",versionId:doc.currentVersionId??null});}
  const questions:Doc<"visitQuestions">[]=[];
  for(const q of await ctx.db.query("visitQuestions").withIndex("by_visitId",q=>q.eq("visitId",visit._id)).take(101)){if((args.questionIds===undefined||args.questionIds.includes(q._id))&&await canReadCareSource(ctx,q.source,ctx.user._id)){questions.push(q);if(q.source.documentId)sources.add(q.source.documentId);}}
  if(questions.length>100)fail("LIMIT","This visit contains too many questions.");
  if(args.questionIds && (args.questionIds.length>100||new Set(args.questionIds).size!==questions.length))fail("NOT_FOUND","One or more selected questions are unavailable.");
  const notes:Doc<"careNotes">[]=[];if((args.noteIds?.length??0)>30)fail("LIMIT","Choose at most thirty notes.");
  for(const id of [...new Set(args.noteIds??[])]){const note=await ctx.db.get(id);if(!note||note.householdId!==args.householdId||!await canReadCareSource(ctx,note.source,ctx.user._id))fail("NOT_FOUND","Selected note unavailable.");notes.push(note);if(note.source.documentId)sources.add(note.source.documentId);}
  const medicines:Doc<"medicineEntries">[]=[];
  if(args.includeMedicines){for(const status of ["current","uncertain"] as const){const rows=await ctx.db.query("medicineEntries").withIndex("by_householdId_and_status",q=>q.eq("householdId",args.householdId).eq("status",status)).take(201);if(rows.length>200)fail("LIMIT","Review the medicine reference before making a pack.");for(const m of rows)if(await canReadCareSource(ctx,m.source,ctx.user._id)){medicines.push(m);if(m.source.documentId)sources.add(m.source.documentId);}}}
  const sourceDocumentIds=[...sources];if(sourceDocumentIds.length>100)fail("LIMIT","Reduce the number of source documents in this pack.");
  const readerIds=await packReaders(ctx,args.householdId,args.readerIds??[],sourceDocumentIds),now=Date.now();
  const visitProvider=visit.providerId?await ctx.db.get(visit.providerId):null;
  const provider=visitProvider?.householdId===args.householdId?{id:visitProvider._id,name:visitProvider.name,role:visitProvider.role,organization:visitProvider.organization,address:visitProvider.address,phone:visitProvider.phone,email:visitProvider.email,version:visitProvider.version,updatedAt:visitProvider.updatedAt}:null;
  const snapshot=JSON.stringify({schemaVersion:1,visit:{provider,id:visit._id,title:visit.title,confirmedStartsAt:visit.confirmedStartsAt,timezone:visit.timezone,confirmedAddress:visit.confirmedAddress,phone:visit.phone,transport:visit.transport??null},summary:text(args.summary,"Visit summary",6000,true),profile:args.includeProfile?{preferredName:profile.preferredName,dateOfBirth:profile.dateOfBirth,allergiesState:profile.allergiesState,allergies:profile.allergies,conditions:profile.conditions,preferences:profile.preferences,communication:profile.communication,emergencyInstructions:profile.emergencyInstructions,insuranceReference:profile.insuranceReference??"",pharmacy:profile.pharmacy??"",reviewedAt:profile.reviewedAt}:null,medicines:medicines.map(m=>({id:m._id,name:m.name,strength:m.strength??"",route:m.route??"",instructions:m.instructions,prescriber:m.prescriber,purpose:m.purpose,status:m.status,reviewNote:m.reviewNote,source:m.source,reviewedAt:m.reviewedAt})),notes:notes.map(n=>({id:n._id,body:n.body,occurredAt:n.occurredAt,source:n.source})),questions:questions.map(q=>({id:q._id,question:q.question,answer:q.answer,status:q.status,source:q.source})),documents,reviewedAt:now,reviewedBy:ctx.user._id});
  if(new TextEncoder().encode(snapshot).length>500000)fail("LIMIT","Reduce the information selected for this visit pack.");
  const latest=await ctx.db.query("visitPacks").withIndex("by_visitId_and_version",q=>q.eq("visitId",visit._id)).order("desc").first();
  const id=await ctx.db.insert("visitPacks",{householdId:args.householdId,visitId:visit._id,summary:text(args.summary,"Visit summary",6000,true),documentIds,sourceDocumentIds,readerIds,includeMedicines:args.includeMedicines,includeProfile:args.includeProfile,reviewedBy:ctx.user._id,reviewedAt:now,snapshot,version:(latest?.version??0)+1,createdBy:ctx.user._id,updatedAt:now});await remember(ctx,"visitPacks",args.requestId,args,id);return id;
 }
});
export const listVisitPacks=userQuery({args:{visitId:v.id("visits")},returns:v.array(schema.doc("visitPacks")),handler:async(ctx,args)=>{const visit=await ctx.db.get(args.visitId);if(!visit)fail("NOT_FOUND","Visit unavailable.");await requireHealthAccess(ctx,visit.householdId);const rows=await ctx.db.query("visitPacks").withIndex("by_visitId_and_version",q=>q.eq("visitId",visit._id)).order("desc").take(50);const allowed=await Promise.all(rows.map(r=>canReadVisitPack(ctx,r,ctx.user._id)));return rows.filter((_,i)=>allowed[i]);}});
export const getVisitPack=userQuery({args:{packId:v.id("visitPacks")},returns:schema.doc("visitPacks"),handler:async(ctx,args)=>{const row=await ctx.db.get(args.packId);if(!row)fail("NOT_FOUND","Visit pack unavailable.");await member(ctx,row.householdId);if(!await canReadVisitPack(ctx,row,ctx.user._id))fail("NOT_FOUND","Visit pack unavailable. Its sharing or source permissions may have changed.");return row;}});
export const setVisitPackReaders=userMutation({args:{packId:v.id("visitPacks"),readerIds:v.array(v.id("users")),expectedVersion:v.number()},returns:v.null(),handler:async(ctx,args)=>{const row=await ctx.db.get(args.packId);if(!row)fail("NOT_FOUND","Visit pack unavailable.");await requireHealthAccess(ctx,row.householdId,true);if(row.createdBy!==ctx.user._id)fail("FORBIDDEN","Only the pack creator can change sharing.");checkVersion(row,args.expectedVersion);if(!await canReadVisitPack(ctx,row,ctx.user._id))fail("SOURCE_ACCESS_REQUIRED","Restore access to the pack's source records before sharing.");const readerIds=await packReaders(ctx,row.householdId,args.readerIds,row.sourceDocumentIds??row.documentIds);await ctx.db.patch(row._id,{readerIds,version:row.version+1,updatedAt:Date.now()});return null;}});

export const listFollowUps=userQuery({args:{...hid,status:followUpStatus,paginationOpts:paginationOptsValidator},returns:paginationResultValidator(schema.doc("followUps").extend({mailUnread:v.boolean()})),handler:async(ctx,args)=>{await requireHealthAccess(ctx,args.householdId);const result=await ctx.db.query("followUps").withIndex("by_householdId_and_status_and_dueAt",q=>q.eq("householdId",args.householdId).eq("status",args.status)).paginate(args.paginationOpts);const page=[];for(const row of result.page)if(await canReadCareSource(ctx,row.source,ctx.user._id))page.push({...await visibleFollowUp(ctx,row,ctx.user._id),mailUnread:await mailUnread(ctx,row,ctx.user._id)});return {...result,page};}});
export const saveFollowUp=userMutation({
 args:{...hid,title:v.string(),detail:v.string(),requestedAt:v.optional(v.number()),contactId:v.optional(v.id("careProviders")),ownerId:v.id("users"),dueAt:v.number(),status:followUpStatus,visitId:v.optional(v.id("visits")),taskId:v.optional(v.id("tasks")),source:referenceSource,resolution:v.string(),followUpId:v.optional(v.id("followUps")),expectedVersion:v.optional(v.number()),requestId:v.string()},returns:v.id("followUps"),
 handler:async(ctx,args)=>{
  await requireHealthAccess(ctx,args.householdId,true);const prior=await priorId(ctx,"followUps",args.requestId,args);if(prior)return prior;
  await activeAssignee(ctx,args.householdId,args.ownerId);if(!await canReadCare(ctx,args.householdId,args.ownerId))fail("CARE_ACCESS_REQUIRED","Choose a follow-up owner with care profile access.");
  await visitFor(ctx,args.householdId,args.visitId);if(args.taskId){const task=await ctx.db.get(args.taskId);if(!task||task.householdId!==args.householdId)fail("NOT_FOUND","Task unavailable.");}
  const old=args.followUpId?await ctx.db.get(args.followUpId):null;if(args.followUpId&&(!old||old.householdId!==args.householdId))fail("NOT_FOUND","Follow-up unavailable.");if(old){checkVersion(old,args.expectedVersion??0);if(!await canReadCareSource(ctx,old.source,ctx.user._id))fail("FORBIDDEN","Source access required.");}
  if(args.contactId){const contact=await ctx.db.get(args.contactId);if(!contact||contact.householdId!==args.householdId)fail("NOT_FOUND","Care contact unavailable.");}
  const source=await sourceFor(ctx,args.householdId,args.source);if(!await canReadCareSource(ctx,source,args.ownerId))fail("SOURCE_ACCESS_REQUIRED","The follow-up owner needs access to its source record.");
  const fields={title:text(args.title,"Title",200),detail:text(args.detail,"Details",4000,true),ownerId:args.ownerId,...(args.requestedAt!==undefined?{requestedAt:timestamp(args.requestedAt)}:{}),...(args.contactId?{contactId:args.contactId}:{}),dueAt:timestamp(args.dueAt),status:args.status,source,resolution:text(args.resolution,"Resolution",4000,args.status==="waiting"),version:(old?.version??0)+1,updatedAt:Date.now(),...(args.visitId?{visitId:args.visitId}:{}),...(args.taskId?{taskId:args.taskId}:{}),...(args.status!=="waiting"?{resolvedAt:Date.now(),resolvedBy:ctx.user._id}:{})};
  const id=old?old._id:await ctx.db.insert("followUps",{...fields,householdId:args.householdId,createdBy:ctx.user._id});if(old)await ctx.db.patch(id,{...fields,visitId:args.visitId,taskId:args.taskId,contactId:args.contactId,requestedAt:args.requestedAt,...(args.status==="waiting"?{resolvedAt:undefined,resolvedBy:undefined}:{})});await remember(ctx,"followUps",args.requestId,args,id);return id;
 }
});

export const availability=userQuery({args:{...hid,from:v.number(),to:v.number()},returns:v.array(schema.doc("memberAvailability")),handler:async(ctx,args)=>{await member(ctx,args.householdId);range(args.from,args.to,93);const rows=await ctx.db.query("memberAvailability").withIndex("by_householdId_and_startsAt",q=>q.eq("householdId",args.householdId).gte("startsAt",Math.max(0,args.from-93*86400000)).lt("startsAt",args.to)).take(501);if(rows.length>500)fail("RANGE_TOO_DENSE","Choose a smaller availability range.");return rows.filter(r=>r.endsAt>args.from);}});
export const saveAvailability=userMutation({args:{...hid,startsAt:v.number(),endsAt:v.number(),state:v.union(v.literal("available"),v.literal("unavailable")),note:v.string(),availabilityId:v.optional(v.id("memberAvailability")),expectedVersion:v.optional(v.number()),requestId:v.string()},returns:v.id("memberAvailability"),handler:async(ctx,args)=>{await member(ctx,args.householdId,false,true);range(args.startsAt,args.endsAt,93);const prior=await priorId(ctx,"memberAvailability",args.requestId,args);if(prior)return prior;const old=args.availabilityId?await ctx.db.get(args.availabilityId):null;if(args.availabilityId&&(!old||old.householdId!==args.householdId||old.userId!==ctx.user._id))fail("FORBIDDEN","Only your own availability can be changed.");if(old)checkVersion(old,args.expectedVersion??0);const fields={startsAt:args.startsAt,endsAt:args.endsAt,state:args.state,note:text(args.note,"Availability note",1000,true),version:(old?.version??0)+1,updatedAt:Date.now()};const id=old?old._id:await ctx.db.insert("memberAvailability",{...fields,householdId:args.householdId,userId:ctx.user._id,createdBy:ctx.user._id});if(old)await ctx.db.patch(id,fields);await remember(ctx,"memberAvailability",args.requestId,args,id);return id;}});
export const removeAvailability=userMutation({args:{availabilityId:v.id("memberAvailability"),expectedVersion:v.number()},returns:v.null(),handler:async(ctx,args)=>{const row=await ctx.db.get(args.availabilityId);if(!row)return null;await member(ctx,row.householdId,false,true);if(row.userId!==ctx.user._id)fail("FORBIDDEN","Only your own availability can be removed.");checkVersion(row,args.expectedVersion);await ctx.db.delete(row._id);return null;}});

export const listReplacements=userQuery({args:{...hid,status:v.union(v.literal("open"),v.literal("accepted"),v.literal("declined"),v.literal("cancelled")),paginationOpts:paginationOptsValidator},returns:paginationResultValidator(schema.doc("replacementRequests")),handler:async(ctx,args)=>{await member(ctx,args.householdId);return ctx.db.query("replacementRequests").withIndex("by_householdId_and_status",q=>q.eq("householdId",args.householdId).eq("status",args.status)).order("desc").paginate(args.paginationOpts);}});
export const requestReplacement=userMutation({
 args:{...hid,target:replacementTarget,targetVersion:v.number(),requestedMemberId:nullableId,reason:v.string(),requestId:v.string()},returns:v.id("replacementRequests"),
 handler:async(ctx,args)=>{
  await member(ctx,args.householdId);const prior=await priorId(ctx,"replacementRequests",args.requestId,args);if(prior)return prior;
  const target=await ctx.db.get(args.target.id);if(!target||target.householdId!==args.householdId)fail("NOT_FOUND","Assignment unavailable.");checkVersion(target,args.targetVersion);
  if(args.target.kind==="task"){const t=target as Doc<"tasks">;if(t.status!=="open"||t.ownerId!==ctx.user._id)fail("FORBIDDEN","Request a replacement for an open task you own.");}
  else{const c=target as Doc<"coverage">;if(c.state!=="committed"||c.plannedOwnerId!==ctx.user._id)fail("INVALID_STATE","Request a replacement for your unstarted commitment. Active care transfers through a handover.");}
  if(args.requestedMemberId){await activeAssignee(ctx,args.householdId,args.requestedMemberId);if(args.requestedMemberId===ctx.user._id)fail("INVALID_ASSIGNEE","Choose another member.");if(args.target.kind==="coverage"&&await isLimitedHelper(ctx,args.householdId,args.requestedMemberId))fail("LIMITED_HELPER_ACCESS","Choose a care-circle member for coverage. Helpers can accept specific task replacements.");}
  const existing=await ctx.db.query("replacementRequests").withIndex("by_target_and_status",q=>q.eq("target",args.target).eq("status","open")).first();if(existing)fail("REQUEST_EXISTS","Resolve the existing replacement request first.");
  const id=await ctx.db.insert("replacementRequests",{householdId:args.householdId,target:args.target,targetVersion:target.version,previousOwnerId:ctx.user._id,requestedMemberId:args.requestedMemberId,reason:text(args.reason,"Reason",1000),status:"open",version:1,createdBy:ctx.user._id,updatedAt:Date.now()});
  const event=await record(ctx,{householdId:args.householdId,actorId:ctx.user._id,type:"replacement.requested",entity:args.target,after:"A replacement was requested. Responsibility remains with the current owner until acceptance."});
  const recipients=args.requestedMemberId?[args.requestedMemberId]:(await ctx.db.query("memberships").withIndex("by_householdId_and_status",q=>q.eq("householdId",args.householdId).eq("status","active")).take(21)).map(m=>m.userId).filter(id=>id!==ctx.user._id);
  for(const userId of recipients)await notify(ctx,{householdId:args.householdId,userId,target:args.target,type:"replacement.requested",dedupeKey:`${event.eventId}:${userId}`,eventId:event.eventId});
  await remember(ctx,"replacementRequests",args.requestId,args,id);return id;
 }
});
export const respondReplacement=userMutation({
 args:{replacementId:v.id("replacementRequests"),expectedVersion:v.number(),operation:v.union(v.literal("accept"),v.literal("decline"),v.literal("cancel"))},returns:v.null(),
 handler:async(ctx,args)=>{
  const row=await ctx.db.get(args.replacementId);if(!row)fail("NOT_FOUND","Replacement request unavailable.");const {household}=await member(ctx,row.householdId);checkVersion(row,args.expectedVersion);if(row.status!=="open")fail("INVALID_STATE","This replacement request is already resolved.");
  if(args.operation==="cancel"){if(row.createdBy!==ctx.user._id&&household.ownerId!==ctx.user._id)fail("FORBIDDEN","Only the requester or household owner can cancel.");}
  else{if(row.previousOwnerId===ctx.user._id||(row.requestedMemberId&&row.requestedMemberId!==ctx.user._id))fail("FORBIDDEN","This replacement request is for another member.");if(args.operation==="decline"&&!row.requestedMemberId)fail("INVALID_STATE","An open request stays available for other volunteers.");}
  if(args.operation==="accept"){
   const target=await ctx.db.get(row.target.id);if(!target||target.householdId!==row.householdId)fail("NOT_FOUND","Assignment unavailable.");checkVersion(target,row.targetVersion);
   if(row.target.kind==="task"){const task=target as Doc<"tasks">;if(task.status!=="open"||task.ownerId!==row.previousOwnerId)fail("CONFLICT","The task assignment changed. Ask for a new replacement request.");await ctx.db.patch(row.target.id,{ownerId:ctx.user._id,requestedOwnerId:null,version:task.version+1,updatedAt:Date.now()});}
   else{const coverage=target as Doc<"coverage">;if(coverage.state!=="committed"||coverage.plannedOwnerId!==row.previousOwnerId)fail("CONFLICT","The coverage changed. Ask for a new replacement request.");await ctx.db.patch(row.target.id,{plannedOwnerId:ctx.user._id,version:coverage.version+1,updatedAt:Date.now()});}
  }
  await ctx.db.patch(row._id,{status:args.operation==="accept"?"accepted":args.operation==="decline"?"declined":"cancelled",resolvedBy:ctx.user._id,resolvedAt:Date.now(),version:row.version+1,updatedAt:Date.now()});
  const event=await record(ctx,{householdId:row.householdId,actorId:ctx.user._id,type:`replacement.${args.operation}`,entity:row.target,after:args.operation==="accept"?"Replacement explicitly accepted; responsibility transferred.":`Replacement ${args.operation}. Existing responsibility is unchanged.`});
  if(row.createdBy!==ctx.user._id)await notify(ctx,{householdId:row.householdId,userId:row.createdBy,target:row.target,type:`replacement.${args.operation}`,dedupeKey:`${event.eventId}:${row.createdBy}`,eventId:event.eventId});return null;
 }
});

export const overview=userQuery({
 args:hid,
 returns:v.object({careAccess:v.boolean(),waitingCount:v.number(),waitingCountLimited:v.boolean(),waiting:v.array(schema.doc("followUps")),notes:v.array(schema.doc("careNotes")),profileReviewedAt:v.union(v.number(),v.null())}),
 handler:async(ctx,args)=>{
  await member(ctx,args.householdId);
  if(!await canReadCare(ctx,args.householdId,ctx.user._id))return {careAccess:false,waitingCount:0,waitingCountLimited:false,waiting:[],notes:[],profileReviewedAt:null};
  const profile=await requireHealthAccess(ctx,args.householdId);
  const waitingRows=await ctx.db.query("followUps").withIndex("by_householdId_and_status_and_dueAt",q=>q.eq("householdId",args.householdId).eq("status","waiting")).take(201);
  const waiting:Doc<"followUps">[]=[];for(const row of waitingRows)if(await canReadCareSource(ctx,row.source,ctx.user._id))waiting.push(await visibleFollowUp(ctx,row,ctx.user._id));
  const recent=await ctx.db.query("careNotes").withIndex("by_householdId_and_occurredAt",q=>q.eq("householdId",args.householdId)).order("desc").take(30);
  const notes:Doc<"careNotes">[]=[];for(const note of recent){if(await canReadCareSource(ctx,note.source,ctx.user._id))notes.push(note);if(notes.length===2)break;}
  return {careAccess:true,waitingCount:waiting.length,waitingCountLimited:waitingRows.length>200,waiting:waiting.slice(0,3),notes,profileReviewedAt:profile.reviewedAt};
 }
});
export const editNote=userMutation({args:{noteId:v.id("careNotes"),expectedVersion:v.number(),body:v.string(),occurredAt:v.number(),visitId:v.optional(v.id("visits")),source:referenceSource},returns:v.null(),handler:async(ctx,args)=>{const row=await ctx.db.get(args.noteId);if(!row)fail("NOT_FOUND","Care note unavailable.");await requireHealthAccess(ctx,row.householdId,true);checkVersion(row,args.expectedVersion);if(!await canReadCareSource(ctx,row.source,ctx.user._id))fail("FORBIDDEN","Source access required.");await visitFor(ctx,row.householdId,args.visitId);await ctx.db.patch(row._id,{body:text(args.body,"Note",6000),occurredAt:timestamp(args.occurredAt),visitId:args.visitId,source:await sourceFor(ctx,row.householdId,args.source),version:row.version+1,updatedAt:Date.now()});return null;}});
