import { defineTable } from "convex/server";
import { v } from "convex/values";
export const recordCategory = v.union(v.literal("report"), v.literal("referral"), v.literal("prescription"), v.literal("discharge"), v.literal("insurance"), v.literal("authority"), v.literal("other"));
export const recordProposalKind = v.union(v.literal("summary"), v.literal("followUp"), v.literal("medicine"), v.literal("question"));
export const recordTables = {
 recordMailOrigins:defineTable({householdId:v.id("households"),recordId:v.id("records"),versionId:v.id("recordVersions"),messageId:v.id("mailMessages"),attachmentId:v.string(),importedBy:v.id("users"),importedAt:v.number()}).index("by_householdId",["householdId"]).index("by_recordId",["recordId"]).index("by_recordId_and_messageId_and_attachmentId",["recordId","messageId","attachmentId"]),
 records: defineTable({ householdId:v.id("households"), title:v.string(), provider:v.optional(v.string()), category:recordCategory, documentDate:v.optional(v.string()), notes:v.string(), readerIds:v.array(v.id("users")), readerGrantedAt:v.optional(v.record(v.id("users"),v.number())), createdBy:v.id("users"), currentVersionId:v.optional(v.id("recordVersions")), status:v.union(v.literal("filed"),v.literal("extracting"),v.literal("review"),v.literal("failed")), version:v.number(), updatedAt:v.number(), workflowId:v.optional(v.string()), extractionBudget:v.optional(v.object({day:v.string(),input:v.number(),output:v.number(),settled:v.boolean()})), safeError:v.optional(v.string()), extractedText:v.optional(v.string()),searchText:v.string() }).index("by_householdId",["householdId"]) .index("by_householdId_and_category",["householdId","category"]).index("by_householdId_and_status",["householdId","status"]).index("by_householdId_and_updatedAt",["householdId","updatedAt"]).searchIndex("search_text",{searchField:"searchText",filterFields:["householdId","category"]}),
 recordVersions: defineTable({ householdId:v.id("households"), recordId:v.id("records"), storageId:v.id("_storage"), filename:v.string(), mimeType:v.string(), bytes:v.number(), uploadedBy:v.id("users"), uploadedAt:v.number(), sha256:v.optional(v.string()), pages:v.optional(v.number()), sourceMessageId:v.optional(v.id("mailMessages")), sourceAttachmentId:v.optional(v.string()) }).index("by_recordId",["recordId"]).index("by_householdId",["householdId"]).index("by_householdId_and_uploadedBy_and_sha256",["householdId","uploadedBy","sha256"]),
 recordProposals: defineTable({ householdId:v.id("households"), recordId:v.id("records"), versionId:v.id("recordVersions"), kind:recordProposalKind, title:v.string(), text:v.string(), quote:v.string(), page:v.number(), status:v.union(v.literal("pending"),v.literal("approved"),v.literal("dismissed")), reviewedBy:v.optional(v.id("users")), reviewedAt:v.optional(v.number()), taskId:v.optional(v.id("tasks")) }).index("by_recordId",["recordId"]).index("by_householdId",["householdId"]).index("by_householdId_and_status",["householdId","status"]).index("by_versionId",["versionId"]).index("by_taskId",["taskId"]),
 recordVisitLinks: defineTable({ householdId:v.id("households"),recordId:v.id("records"),visitId:v.id("visits"),createdBy:v.id("users"),createdAt:v.number() }).index("by_recordId",["recordId"]).index("by_visitId",["visitId"]).index("by_recordId_and_visitId",["recordId","visitId"]).index("by_householdId",["householdId"]),
 recordShares: defineTable({ householdId:v.id("households"),recordId:v.id("records"),versionId:v.id("recordVersions"),recipientEmail:v.string(),createdBy:v.id("users"),createdAt:v.number(),expiresAt:v.number(),revokedAt:v.optional(v.number()) }).index("by_recordId",["recordId"]).index("by_householdId",["householdId"]).index("by_recipientEmail_and_expiresAt",["recipientEmail","expiresAt"]),
};
