import { $,esc,button,badge,empty,skeleton,area,select,modal as baseModal,formatDate,dateFields,resolveDate,replaceContent } from '../ui/core.js';
import { header,paginated,toast } from '../ui/session.js';

function modal(ctx,options){const dialog=baseModal({ctx,...options});const stop=ctx.add(()=>{if(dialog.isConnected)dialog.close();});dialog.addEventListener('close',stop,{once:true});return dialog;}
const stamp=(ctx,value,zone)=>value?formatDate(value,zone||ctx.household.timezone):'Not confirmed';
function fact(label,value){return value?`<div><dt>${esc(label)}</dt><dd>${esc(value)}</dd></div>`:'';}
function errandDetails(task){
 const p=task.place;if(!p)return '';if(!p.locationShared)return '<p class="ui-notice attention">The errand location has not been shared with you. Ask the coordinator for the practical details.</p>';
 const phone=String(p.phone||'').replace(/[^\d+() -]/g,'');return `<details class="helper-travel"><summary>Errand location</summary><dl class="helper-facts">${fact('Place',p.name)}${fact('Address',p.address)}${fact('Entrance',p.entrance)}${fact('Parking',p.parking)}${fact('Access',p.accessibility)}${fact('Phone',p.phone)}</dl><div class="ui-actions"><a class="ui-button secondary" href="https://maps.apple.com/?q=${encodeURIComponent(p.address)}" target="_blank" rel="noopener noreferrer">Directions ↗</a>${phone?`<a class="ui-button secondary" href="tel:${esc(phone)}">Call contact</a>`:''}</div></details>`;
}
function travelDetails(ctx,task){
 const v=task.visit;if(!v)return errandDetails(task);
 const date=value=>value?stamp(ctx,value,v.timezone):'';
 const phone=String(v.phone||'').replace(/[^\d+() -]/g,'');
 return `<details class="helper-travel"><summary>Travel & contact details</summary>${v.locationShared===false?'<p class="ui-notice attention">This location has not been shared with you. Ask the coordinator for the practical arrangements before travelling.</p>':''}<dl class="helper-facts">${fact('Visit status',v.status==='cancelled'?'Cancelled':v.status==='completed'?'Completed':'Upcoming')}${fact('Visit time',date(v.when))}${fact('Destination',v.address)}${fact('Pickup address',v.pickupAddress)}${fact('Pickup time',date(v.pickupAt))}${fact('Arrive by',date(v.arrivalAt))}${fact('Return pickup',date(v.returnAt))}${fact('Return address',v.returnAddress)}${fact('Access needs',v.accessibilityNote)}${fact('Accompanying arrangements',v.accompanyingNote)}${fact('Entrance',v.entrance)}${fact('Parking',v.parking)}${fact('Contact phone',v.phone)}</dl><div class="ui-actions">${v.address?`<a class="ui-button secondary" href="https://maps.apple.com/?q=${encodeURIComponent(v.address)}" target="_blank" rel="noopener noreferrer">Open destination in Maps ↗</a>`:''}${phone?`<a class="ui-button secondary" href="tel:${esc(phone)}">Call contact</a>`:''}</div></details>`;
}
function taskAction(ctx,task,operation){
 const labels={accept:'Accept responsibility',decline:'Decline request',complete:'Mark complete',release:'Release responsibility'};
 const descriptions={accept:'You will become responsible for this task. The family will see your acceptance.',decline:'This request will be declined. You will not become responsible for it.',complete:'Confirm that this responsibility is finished. The family will see it as complete.',release:'This task will become unassigned so the family can arrange someone else. It will not be marked complete.'};
 modal(ctx,{title:labels[operation]+'?',content:`<p><strong>${esc(task.title)}</strong></p><p>${descriptions[operation]}</p>`,submit:labels[operation],onSubmit:async()=>{await ctx.mutate('helpers:respond',{taskId:task._id,expectedVersion:task.version,operation});toast({accept:'Responsibility accepted.',decline:'Request declined.',complete:'Responsibility completed.',release:'Responsibility released.'}[operation]);}});
}
function responsibilities(ctx,root,lane){
 paginated(ctx,root,'helpers:home',{householdId:ctx.id,lane},(el,rows)=>{
  replaceContent(el,rows.length?rows.map(task=>`<article class="helper-task" data-key="${esc(task._id)}"><div class="ui-section-heading"><h3>${esc(task.title)}</h3>${badge(lane==='requested'?'Your acceptance needed':lane==='done'?'Completed':lane==='cancelled'?'Cancelled':'Accepted',lane==='requested'?'attention':lane==='done'?'success':'neutral')}</div><p class="ui-hint">${task.travelRole?esc({outbound:'Outbound ride',return:'Return ride',accompany:'Accompanying'}[task.travelRole])+' · ':''}${task.dueAt?'Due '+esc(stamp(ctx,task.dueAt)):'No due time set'}</p>${lane==='requested'&&task.visit?'<p class="ui-hint">Review the current visit and pickup times before accepting, including any revised arrangements.</p>':''}${task.note?`<p class="detail-prose">${esc(task.note)}</p>`:''}${travelDetails(ctx,task)}${['done','cancelled'].includes(lane)?'':`<div class="ui-actions">${lane==='requested'?button('Accept','accept','primary')+button('Decline','decline'):button('Mark complete','complete','primary')+button('Release','release')}</div>`}</article>`).join(''):empty(lane==='requested'?'No requests waiting.':lane==='mine'?'Nothing assigned to you.':lane==='cancelled'?'No cancelled responsibilities.':'No completed responsibilities.',lane==='requested'?'New requests will appear here. You choose whether to accept them.':lane==='mine'?'Accept a request to take responsibility for it.':lane==='cancelled'?'Cancelled journeys and other cancelled responsibilities remain here for reference.':'The responsibilities you finish will appear here.'));
  el.onclick=event=>{const b=event.target.closest('[data-action]');if(!b)return;const task=rows.find(t=>t._id===b.closest('[data-key]')?.dataset.key);if(task&&['accept','decline','complete','release'].includes(b.dataset.action))taskAction(ctx,task,b.dataset.action);};
 });
}
function availabilityForm(ctx,item){
 const requestId=crypto.randomUUID();
 modal(ctx,{title:item?'Edit your availability':'Add your availability',content:select('state','You are',[['available','Available to help'],['unavailable','Unavailable']],item?.state||'available')+'<h3>From</h3>'+dateFields(item?.startsAt||Date.now(),ctx.household.timezone,'start')+'<h3>Until</h3>'+dateFields(item?.endsAt||Date.now()+3600000,ctx.household.timezone,'end')+area('note','What the family should know',item?.note||'','maxlength="1000"')+'<p class="ui-hint">Your availability is shared with the care circle. It does not change your accepted responsibilities.</p>',onSubmit:async data=>{
  const startsAt=await resolveDate(ctx,data.get('startDate'),data.get('startTime'),ctx.household.timezone,data.get('startChoice'));
  const endsAt=await resolveDate(ctx,data.get('endDate'),data.get('endTime'),ctx.household.timezone,data.get('endChoice'));
  if(!startsAt||!endsAt||endsAt<=startsAt)throw {data:{message:'Choose an end time after the start.'}};
  await ctx.mutate('care:saveAvailability',{householdId:ctx.id,...(item?{availabilityId:item._id,expectedVersion:item.version}:{}),startsAt,endsAt,state:data.get('state'),note:data.get('note'),requestId});toast('Availability saved.');
 }});
}
export function helperPage(ctx){
 header(ctx,'My responsibilities',`Help ${ctx.household.nickname} with the things you’ve agreed to take on.`);
 const root=$('#view-body');
 root.innerHTML=`<div class="helper-layout"><div><section class="ui-section"><h2>Waiting for your answer</h2><div data-helper-requested>${skeleton()}</div><h3>Requests to cover for someone</h3><div data-helper-replacements>${skeleton()}</div></section><section class="ui-section"><h2>Accepted by you</h2><div data-helper-mine>${skeleton()}</div></section><section class="ui-section"><h2>Completed</h2><div data-helper-done>${skeleton()}</div></section><section class="ui-section"><h2>Cancelled</h2><div data-helper-cancelled>${skeleton()}</div></section></div><aside class="care-aside"><section><h2>Your part in the care circle</h2><p>You have limited helper access. Only your requested or accepted responsibilities and the practical details needed for them appear here.</p><p class="ui-hint">${ctx.household.ownerName?esc(ctx.household.ownerName)+' manages this household.':''} Medical records and private conversations stay with the care circle.</p></section><section><div class="ui-section-heading"><h2>Your availability</h2>${button('Add','availability')}</div><p class="ui-hint">Current and upcoming availability for the next 90 days. Shared with the care circle.</p><div data-helper-availability>${skeleton()}</div></section><section><h3>Need to step away?</h3><p>Release individual responsibilities above, or leave this household.</p>${button('Leave household','leave')}</section></aside></div>`;
 for(const lane of ['requested','mine','done','cancelled'])responsibilities(ctx,root.querySelector('[data-helper-'+lane+']'),lane);
 replacements(ctx,root.querySelector('[data-helper-replacements]'));
 root.querySelector('[data-action="availability"]').onclick=()=>availabilityForm(ctx);
 root.querySelector('[data-action="leave"]').onclick=()=>modal(ctx,{title:'Leave this household?',content:'<p>You will lose access immediately. Your unfinished responsibilities remain attributed to you until the care circle explicitly reassigns them.</p>',submit:'Leave household',destructive:true,onSubmit:async()=>{await ctx.mutate('helpers:leave',{householdId:ctx.id});ctx.go('/households'+(ctx.auth.sampleSession?'?sample=1':''));}});
 const el=root.querySelector('[data-helper-availability]'),from=Date.now();
 ctx.watch('helpers:availability',{householdId:ctx.id,from,to:from+90*86400000},rows=>{
  replaceContent(el,rows.length?rows.map(item=>`<article class="helper-availability" data-key="${esc(item._id)}"><strong>${item.state==='available'?'Available to help':'Unavailable'}</strong><p class="ui-hint">${esc(stamp(ctx,item.startsAt))} – ${esc(stamp(ctx,item.endsAt))}</p>${item.note?`<p class="detail-prose">${esc(item.note)}</p>`:''}<div class="ui-actions">${button('Edit','edit')}${button('Remove','remove')}</div></article>`).join(''):empty('No availability added.','Share when you can help.'));
  el.onclick=event=>{const b=event.target.closest('[data-action]');if(!b)return;const item=rows.find(a=>a._id===b.closest('[data-key]')?.dataset.key);if(!item)return;if(b.dataset.action==='edit')availabilityForm(ctx,item);if(b.dataset.action==='remove')modal(ctx,{title:'Remove your availability?',content:'<p>This time window will no longer appear in the family’s availability.</p>',submit:'Remove',onSubmit:async()=>{await ctx.mutate('care:removeAvailability',{availabilityId:item._id,expectedVersion:item.version});toast('Availability removed.');}});};
 },error=>{el.innerHTML=empty('Availability is unavailable.','Reload this page to try again.');ctx.error(error);});
}

function replacements(ctx,root){
 paginated(ctx,root,'helpers:replacements',{householdId:ctx.id},(el,rows)=>{
  replaceContent(el,rows.length?rows.map(r=>`<article class="helper-task" data-key="${esc(r._id)}"><div class="ui-section-heading"><h3>${esc(r.title)}</h3>${badge('Cover requested','attention')}</div><p class="ui-hint">${r.dueAt?'Due '+esc(stamp(ctx,r.dueAt)):'No due time set'}. The current person stays responsible until you accept.</p>${r.note?`<p class="detail-prose">${esc(r.note)}</p>`:''}${travelDetails(ctx,r)}<div class="ui-actions">${button('Accept cover','accept','primary')}${button('Decline','decline')}</div></article>`).join(''):empty('No requests for cover.','Requests directed to you will appear here.'));
  el.onclick=event=>{const b=event.target.closest('[data-action]'),r=b&&rows.find(item=>item._id===b.closest('[data-key]')?.dataset.key);if(!r||!['accept','decline'].includes(b.dataset.action))return;const operation=b.dataset.action;modal(ctx,{title:operation==='accept'?'Take over this responsibility?':'Decline this request?',content:`<p><strong>${esc(r.title)}</strong></p><p>${operation==='accept'?'This responsibility will transfer to you when you accept.':'The current person will remain responsible.'}</p>`,submit:operation==='accept'?'Accept responsibility':'Decline request',onSubmit:async()=>{await ctx.mutate('helpers:respondReplacement',{replacementId:r._id,expectedVersion:r.version,operation});toast(operation==='accept'?'Responsibility accepted.':'Cover request declined.');}});};
 });
}
