import { zoneChange } from './timezone.js';
import { $,esc,link,button,badge,empty,field,area,select,modal,formatDate,wireForm,notice,allPages,replaceContent } from '../ui/core.js';
import { header,paginated,toast } from '../ui/session.js';
export async function contactForm(ctx,contact=null,seed={}){
 if(!contact&&seed.email){try{const groups=await Promise.all(['approved','blocked'].map(state=>allPages(ctx,'contacts:list',{householdId:ctx.id,state},201)));if(!ctx.alive)return;contact=groups.flat().find(c=>c.email.toLowerCase()===seed.email.toLowerCase())??null;}catch(error){ctx.error(error);return;}}
 modal({ctx,title:contact?'Edit contact permissions':'Approve a contact',content:field('label','Name',contact?.label??seed.label??'','text','required maxlength="120"')+field('email','Email',contact?.email??seed.email??'','email',`required maxlength="254" ${contact?'readonly':''}`)+area('relationship','Why this contact is approved',contact?.relationship??'','required maxlength="1000"')+['allowSend','allowReceive','allowReply'].map(name=>`<label class="ui-check"><input type="checkbox" name="${name}" ${contact?.[name]?'checked':''}><span>${{allowSend:'Allow new questions to this address',allowReceive:'Allow messages from this actual sender',allowReply:'Allow replies to this actual sender'}[name]}</span></label>`).join('')+select('state','Contact status',[['approved','Approved'],['blocked','Blocked']],contact?.state??'approved')+'<p class="ui-hint">A forwarded message’s author is not automatically an approved sender. Permission changes sync to the household mailbox.</p>',submit:'Save permissions',onSubmit:async d=>{await ctx.mutate('contacts:set',{householdId:ctx.id,...(contact?{expectedVersion:contact.version}:{}),label:d.get('label'),email:d.get('email'),relationship:d.get('relationship'),allowSend:!!d.get('allowSend'),allowReceive:!!d.get('allowReceive'),allowReply:!!d.get('allowReply'),state:d.get('state')});toast('Contact permissions saved.');}});}
export function mailStatus(ctx,root){ctx.watch('inbox:connection',{householdId:ctx.id},account=>{root.innerHTML=!ctx.household.emailImport?`<div class="ui-notice">Email import is off. ${link(ctx.path('/settings?section=sharing'),'Review sharing choices')}</div>`:account?.status==='ready'&&account.address?`<div class="mail-address"><div><strong>Household email</strong><p>${esc(account.address)}</p><p class="ui-hint">Forward logistics from an approved sender. Contacts sync: ${esc(account.contactSyncState)}.</p></div>${button('Copy address','copy-address')}${account.contactSyncState==='failed'?button('Retry contact sync','sync'):''}</div>`:`<div class="ui-notice ${account?.status==='failed'?'error':'attention'}"><strong>${account?.status==='failed'?(account.capacityReached?'Email setup is waiting for capacity':'Mailbox setup needs attention'):'Preparing your household mailbox'}</strong><p>${esc(account?.lastError||'You can continue using responsibilities and handovers while mail is being prepared.')}</p>${account?.status==='failed'?button(account.capacityReached?'Check email availability':'Retry mailbox setup','provision'):''}</div>`;root.onclick=async event=>{const b=event.target.closest('[data-action]');if(!b)return;b.disabled=true;try{if(b.dataset.action==='copy-address'){await navigator.clipboard.writeText(account.address);toast('Household email copied.');}else await ctx.action(b.dataset.action==='sync'?'mail:syncContactPolicies':'mail:provision',{householdId:ctx.id});}catch(e){ctx.error(e);}finally{if(b.isConnected)b.disabled=false;}};},ctx.error);}
export function settings(ctx){
 const section=new URLSearchParams(location.search).get('section')||'household';header(ctx,'Settings','Your household, your choices.');const root=$('#view-body');root.innerHTML=`<div class="settings-layout"><nav aria-label="Settings sections">${[['household','Household'],['sharing','Sharing & processing'],['email','Email & contacts'],['notifications','Notifications'],['data','Your data']].map(([id,label])=>`<a data-route href="${ctx.path('/settings?section='+id)}" ${section===id?'aria-current="page"':''}>${label}</a>`).join('')}</nav><section id="settings-content"></section></div>`;const content=$('#settings-content');
 if(section==='household'){householdSettings(ctx,content);return;}
 if(section==='sharing'){content.innerHTML=`<h2>Sharing & processing</h2><p class="ui-hint">Care-circle members share responsibilities and visits. Records have individual readers; care essentials and the inbox follow your care permissions. Limited helpers see their assignments. Optional processing choices can be withdrawn.</p>${[['emailImport','Email import','AgentMail processes your care inbox, forwarded messages and attachments, and email you explicitly approve for sending.'],['aiProcessing','AI assistance','Google Gemini processes selected text, PDFs and images to propose source-linked information and draft text for your review.']].map(([scope,title,copy])=>`<section class="detail-card"><div class="ui-section-heading"><h2>${title}</h2>${badge(ctx.household[scope]?'Enabled':'Off',ctx.household[scope]?'success':'neutral')}</div><p>${copy}</p><p class="ui-hint">${scope==='emailImport'?'Withdrawal stops future email processing.':'Suggestions never change confirmed details or send mail without review.'} Existing records are retained until their normal expiry or deletion.</p>${ctx.isOwner?button(ctx.household[scope]?'Turn off':'Enable',scope):'<p>Only the household owner can change this choice.</p>'}</section>`).join('')}${link('/consumer-health-privacy','Read the care-data notice')}`;content.onclick=e=>{const b=e.target.closest('[data-action]');if(!b)return;const scope=b.dataset.action,granted=!ctx.household[scope];modal({ctx,title:`${granted?'Enable':'Turn off'} ${scope==='emailImport'?'email import':'AI assistance'}?`,content:granted?'<label class="ui-check"><input name="authority" type="checkbox" required><span>I have permission or authority to use this optional processing for our shared household information.</span></label>':'<p>Future processing stops. Existing records are not automatically erased. Use Your data to request deletion.</p>',submit:granted?'Enable processing':'Turn off',onSubmit:async()=>{await ctx.mutate('consents:set',{householdId:ctx.id,scope,granted,noticeVersion:'2026-09-care-records',authorityStatement:'Household owner confirmed authority for the selected processing choice.'});ctx.go(ctx.path('/settings?section=sharing'));}});};return;}
 if(section==='email'){content.innerHTML=`<h2>Email & contacts</h2><div id="settings-mail"></div><p class="ui-hint">Forward only logistics your household is authorized to share. Confirm the actual sender as a contact before importing their messages.</p><div class="ui-actions">${button('Approve contact','contact','primary')}</div>${['approved','blocked'].map(state=>`<section class="ui-section"><h2>${state==='approved'?'Approved contacts':'Blocked contacts'}</h2><div id="contacts-${state}"></div></section>`).join('')}`;mailStatus(ctx,$('#settings-mail'));$('[data-action="contact"]').onclick=()=>contactForm(ctx);for(const state of ['approved','blocked'])paginated(ctx,$('#contacts-'+state),'contacts:list',{householdId:ctx.id,state},(el,rows)=>{el.innerHTML=rows.length?rows.map(c=>`<div class="ui-list-row"><div class="row-main"><strong>${esc(c.label)}</strong><div class="row-meta">${esc(c.email)}</div><p class="ui-hint">${c.allowSend?'Send allowed':'No new sends'} · ${c.allowReceive?'Receive allowed':'Receive blocked'} · ${c.allowReply?'Reply allowed':'No replies'}</p></div>${button('Edit',c._id)}</div>`).join(''):empty('No '+state+' contacts.','Only explicitly approved directions are allowed.');el.onclick=e=>{const b=e.target.closest('[data-action]');if(b)contactForm(ctx,rows.find(c=>c._id===b.dataset.action));};});return;}
 if(section==='notifications'){notificationSettings(ctx,content);return;}
 content.innerHTML=`<h2>Your household data</h2><p class="ui-hint">An export contains the household data you are authorized to access, collected over the export interval. It is a private NDJSON archive, not a frozen snapshot.</p><div class="ui-actions">${button('Export household data','export','primary')}${link('/privacy-requests'+(ctx.auth.sampleSession?'?sample=1':''),'My requests','ui-button secondary')}</div><section class="detail-card"><h2>Retention</h2><p>Active work keeps the context it needs. Completed operational history is normally retained for 90 days; raw source evidence follows its own retention and active-reference rules.</p>${link('/privacy','Read the retention policy')}</section>${ctx.isOwner?`<section class="detail-card"><h2>Delete household</h2><p>This immediately removes normal access, then cleans up supported processors. You can follow its progress from My requests.</p><p class="ui-hint">Copies received outside Handoff cannot be recalled. This does not delete your entire account.</p>${button('Delete household','delete','danger')}</section>`:''}`;
 content.onclick=e=>{const b=e.target.closest('[data-action]');if(!b)return;const kind=b.dataset.action,requestId=crypto.randomUUID();modal({ctx,title:kind==='delete'?'Permanently delete this household?':'Export household data?',content:kind==='delete'?'<label class="ui-check"><input type="checkbox" required><span>I understand that this removes household access immediately and permanently deletes the household’s supported data.</span></label>':'<p>Your export will be available only to your signed-in account while you retain household access. Download it before it expires.</p>',submit:kind==='delete'?'Delete household':'Create export',destructive:kind==='delete',onSubmit:async()=>{const id=await ctx.mutate('privacyJobs:request',{householdId:ctx.id,kind,confirmed:true,requestId});ctx.go('/privacy-requests/'+id+(ctx.auth.sampleSession?'?sample=1':''));}});};
}

function householdSettings(ctx,content){
 content.innerHTML='<h2>Household details</h2><form id="household-form">'+field('nickname','Household nickname',ctx.household.nickname,'text','required maxlength="80"')+'<div data-household-facts></div><div class="ui-form-status"></div><div class="ui-actions" data-household-actions></div></form>';
 const form=$('#household-form'),input=$('[name="nickname"]',form);
 wireForm(ctx,form,async data=>{await ctx.mutate('households:rename',{householdId:ctx.id,nickname:data.get('nickname')});toast('Household nickname saved.');});
 function render(household){
  ctx.household=household;ctx.isOwner=household.ownerId===ctx.viewer.id;input.disabled=!ctx.isOwner;
  if(form.dataset.dirty!=='true')input.value=household.nickname;
  replaceContent($('[data-household-facts]',form),'<p class="ui-hint">Time zone: '+esc(household.timezone)+'</p><p class="ui-hint">Owner: '+esc(ctx.name(household.ownerId))+'</p>');
  replaceContent($('[data-household-actions]',form),ctx.isOwner?'<button class="ui-button primary" type="submit">Save nickname</button>'+button('Change time zone','timezone'):'<p>Only the household owner can change these settings.</p>');
 }
 $('[data-household-actions]',form).onclick=event=>{if(event.target.closest('[data-action="timezone"]'))zoneChange(ctx);};
 ctx.watch('households:get',{householdId:ctx.id},render,ctx.unavailable);render(ctx.household);
}

function notificationSettings(ctx,content){
 const eligible=!ctx.viewer.anonymous&&ctx.viewer.verified&&ctx.household.mode!=='demo';
 content.innerHTML=`<h2>Your notifications</h2><p class="ui-hint">In-app updates are personal. Optional email reminders contain a generic prompt to open Handoff, without care details.</p><form id="notification-form"><p>${esc(ctx.viewer.email||'Sample account')}</p><label class="ui-check"><input name="emailNotifications" type="checkbox" aria-describedby="notification-eligibility"><span>Send me generic email reminders</span></label><p id="notification-eligibility" class="ui-hint">${eligible?'You can turn email reminders off at any time.':ctx.household.mode==='demo'?'Email reminders are unavailable in the fictional sample. In-app updates still work.':'Email reminders require a verified real account.'}</p><div class="ui-form-status" aria-live="polite"></div><button class="ui-button primary" type="submit">Save preference</button></form>`;
 const form=$('#notification-form'),input=form.elements.emailNotifications,submit=$('[type="submit"]',form);
 function render(members){
  const own=members.find(m=>m.membership.userId===ctx.viewer.id);
  const saved=!!own?.membership.emailNotifications;
  // Keep an existing opt-in removable even if this account is no longer eligible.
  input.disabled=!eligible&&!saved;submit.hidden=input.disabled;
  if(form.dataset.dirty!=='true')input.checked=saved;
 }
 render(ctx.members);
 wireForm(ctx,form,async d=>{await ctx.mutate('notifications:preferences',{householdId:ctx.id,emailNotifications:!!d.get('emailNotifications')});toast('Notification preference saved.');});
 ctx.watch('team:list',{householdId:ctx.id},team=>render(team.members),ctx.error);
}
